#index:
#    path: /
#    controller: App\Controller\DefaultController::index

controllers:
    resource: '../src/Controller'
    type:     annotation




#images_print:

#exemple
#nombre2:
    #path: /nombre2/{max}
    #controller: App\Controller\ChanceController::nombre2
    #methods: GET
    
#nombre_show:
#    path: /nombre/{slug}
#    controller: App\Controller\ChanceController::show


#nombre_random:
#    -> (chemin) path: /nombre
#    -> the controller value has the format 'ControllerClass::nom_methode'
#    controller: App\Controller\ChanceController::nombre