#index:
#    path: /
#    controller: App\Controller\DefaultController::index

controllers:
    resource: '../src/Controller/'
    type:     annotation

account:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

#exemple
nombre2:
    path: /nombre2/{max}
    controller: App\Controller\ChanceController::nombre2
    methods: GET
    
#nombre_show:
#    path: /nombre/{slug}
#    controller: App\Controller\ChanceController::show

nombre_list: #Ou suppresion de requirements et ajout de \d+ dans le path: /nombre/{page<\d+>}
    path: /nombre/{page}  
    controller: App\Controller\ChanceController::list
    #defaults: Exemple possible
        #page: 1
    requirements:
        page: '\d+'

#nombre_random:
#    -> (chemin) path: /nombre
#    -> the controller value has the format 'ControllerClass::nom_methode'
#    controller: App\Controller\ChanceController::nombre