<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBCMxoMq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBCMxoMq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBCMxoMq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBCMxoMq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBCMxoMq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BCMxoMq',
    'container.build_id' => '3908a7eb',
    'container.build_time' => 1580195208,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBCMxoMq');
