<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'app_back_admin' => [[], ['_controller' => 'App\\Controller\\Back\\AdminController::menu'], [], [['text', '/admin']], [], []],
    'app_back_admin_project' => [[], ['_controller' => 'App\\Controller\\Back\\ProjectController::index'], [], [['text', '/admin/project/']], [], []],
    'app_back_admin_project_new' => [[], ['_controller' => 'App\\Controller\\Back\\ProjectController::newProject'], [], [['text', '/admin/project/new']], [], []],
    'app_back_admin_project_print' => [['id'], ['_controller' => 'App\\Controller\\Back\\ProjectController::printProject'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/project']], [], []],
    'app_back_admin_project_edit' => [['id'], ['_controller' => 'App\\Controller\\Back\\ProjectController::editProject'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/admin/project']], [], []],
    'app_back_admin_project_delete' => [['id'], ['_controller' => 'App\\Controller\\Back\\ProjectController::deleteProject'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id'], ['text', '/admin/project']], [], []],
    'app_back_admin_project_deleteImage' => [['id'], ['_controller' => 'App\\Controller\\Back\\ProjectController::deleteImage'], [], [['text', '/deleteImage/'], ['variable', '/', '[^/]++', 'id'], ['text', '/admin/project']], [], []],
    'app_back_login' => [[], ['_controller' => 'App\\Controller\\Back\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\Back\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'app_back_admin_skill' => [[], ['_controller' => 'App\\Controller\\Back\\SkillController::index'], [], [['text', '/admin/skill/']], [], []],
    'app_back_admin_skill_create' => [[], ['_controller' => 'App\\Controller\\Back\\SkillController::newSkill'], [], [['text', '/admin/skill/create']], [], []],
    'app_back_admin_skill_print' => [['id'], ['_controller' => 'App\\Controller\\Back\\SkillController::printSkill'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/skill']], [], []],
    'app_back_admin_skill_delete' => [['id'], ['_controller' => 'App\\Controller\\Back\\SkillController::deleteSkill'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id'], ['text', '/admin/skill']], [], []],
    'app_back_admin_skill_edit' => [['id'], ['_controller' => 'App\\Controller\\Back\\SkillController::editSkill'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/admin/skill']], [], []],
    'app_front_home_home' => [[], ['_controller' => 'App\\Controller\\Front\\HomeController::home'], [], [['text', '/']], [], []],
    'app_front_project_projects' => [[], ['_controller' => 'App\\Controller\\Front\\ProjectController::projects'], [], [['text', '/projets']], [], []],
];
